version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_GROUP_ID: transaction-group # This is just an example, GROUP_ID is not used at broker level
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    command: >
      /bin/sh -c "
      echo '{\"actionType\":\"DEPOSIT\",\"action\":\"User deposit\",\"beforeBalance\":1000.0,\"amount\":200.0,\"afterBalance\":1200.0,\"roundId\":\"R12345\",\"gameId\":\"G12345\",\"gameName\":\"Starburst\",\"gameCategory\":\"Slots\",\"endRound\":true,\"username\":\"user123\",\"upline\":\"uplineUser\",\"refSale\":\"refSale123\",\"description\":\"User made a deposit\",\"productId\":\"P12345\",\"productName\":\"ProductName\",\"provider\":\"NetEnt\",\"percentage\":10.0,\"syncDate\":\"2023-11-05T20:01:39Z\",\"createdAt\":\"2023-11-05T20:01:39Z\",\"createdAtIso\":\"2023-11-05T20:01:39Z\",\"created\":\"2023-11-05T20:01:39\",\"ip\":\"192.168.1.1\",\"frunning\":false,\"featureBuy\":false,\"frunningDate\":\"2023-11-05T20:01:39Z\"}' | kafka-console-producer --broker-list kafka:9092 --topic transaction
      "

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
